### ISSUE TITLE
Order Book: Make it more clear what's the GREEN and what's the RED

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1054]
So when you see market DAI-WETH, what you see in the green/red parts of the graph is:

**GREEN**
* Is people selling WETH-DAI (directly or up to 2 hops)
* So as seller of market DAI-WETH, it's what you are most interested in
* The volume is given in DAI --> makes sense, you are selling DAI so it's more convenient to you to know up to how much volume you can sell for each price point
* The price is given in WETH --> make sense, you are selling in DAI-WETH so from your perspective, your quote is in WETH. Having said that. Probably makes sense to show the inverse price too for reference.

**RED**
* Is other people (like you), trying yo sell DAI-WETH
* Volume is in DAI --> make sense
* Price is in WETH --> make sense

## Proposal
![image](https://user-images.githubusercontent.com/2352112/82889167-a0a84500-9f4a-11ea-9f0e-1cd7eb4a21c3.png)

For the example above ☝️, some simple changes would be to change the pop up to say:

---

   **WETH-DAI Bids**
   Price: 0.00308... WETH
   Price: 324.675... DAI
   Volume: 9,421.7 DAI

---

The RED part would say:

---

   **DAI-WETH Asks**
   Price: 0.00370... WETH
   Price: 270.270... DAI
   Volume: 3,523.123 DAI

---

**Comment by anxolin** [comment]
cc/ @Rafanator @koeppelmann @c3rnst @alfetopito @bh2smith @fleupold

**Comment by bh2smith** [comment]
> X-Y Bids
I am still very much confused by this. Would we put an arrow here? `X->Y Bids` and what up with `Y-X Asks` isnt that the same as `X-Y Bids` (like if we swap X, Y and change bid to ask)... what is this!?

**Comment by Rafanator** [comment]
@anxolin We should keep it as it currently is. Why: 

- When you are in `View Order Book`, you are already in the context of one token pair (DAI-WETH in your example). 
- Adding an additional price would be out of context, since the `X` axis expresses the price of the token pair you selected before (DAI-WETH in your example).

I also created an additional issue as currently  [`View Order Book` displays the Order Book of the opposite pair](https://github.com/gnosis/dex-react/issues/1056).

**Comment by anxolin** [comment]
I'll close this issue, let's move the discussion to this PR where I've made a proposal that tries to address the issues: https://github.com/gnosis/dex-react/pull/1062 (there's a DEMO url there)
