### ISSUE TITLE
Limit Price is Confusing to Users

### ISSUE THREAD

**Issue by jpkcambridge** [gnosis/dex-react#1132]
Some users are placing the inverse of the limit price they actually intend due to confusion about which box has the quote currency they intend to use.  Could be better to have one box with the price in the quote currency.  For example instead of what is shown in the screenshot below, just have one box with the price "0.36 USDT"

<img width="533" alt="Screen Shot 2020-06-20 at 9 35 18 PM" src="https://user-images.githubusercontent.com/874683/85214802-00252500-b33e-11ea-80de-5c4fd732363d.png">

**Comment by koeppelmann** [comment]
@jpkcambridge the problem is that it is very hard to make a general rule for this.
Agree, in this case, the 0.36 representation is more intuitive but e.g. what in a USDT/DAI use case

What does a price 1.02 express here? 
As soon as you fill in the "sell" amount it will fill in the "receive" amount and that should make it in principal clear.

**Comment by jpkcambridge** [comment]
The price would be in the quote currency, so 1.02 DAI would be the amount of DAI you are paying for 1 USDT.  Examples of this are https://loopring.io/trade/USDT-DAI and https://pro.coinbase.com/trade/DAI-USDC (Couldn't find USDT on Coinbase)

Of course it would make sense for a user to verify the sell and receive amounts make sense, but I think the goal should be to stick to popular conventions and make it as clear as possible.

**Comment by besoeasy** [comment]
no limit price makes perfect sense, if someone can install metamask and enable coins he can understand limit order.

limit order is general term used widely while trading

**Comment by anxolin** [comment]
We brought that up several times. I think the underlying issue is that normally exchanges decide for each token pair, which one is base and which one is quote.
In Mesa, there’s no such a thing, anyone can list any token pair. Actually, this would make a nice addition dxDAO, defining the markets in a decentralized way.

If you set the base/quote in a canonical way, then you could sell/buy for that market. The price would refer always to the quote, and people would get less confusion.

If the UI cannot decide which is the quote, you could see "SELL A for B" order as:
- Sell in A-B market (so price is given in B => you are interested in the UI's left price)
- Buy in B-A market (so price is given in A => you are interested in the UI's right price)

**Comment by anxolin** [comment]
About the solution, it might be good to show just one price, but I think probably wouldn't solve the issue for everyone, imagine for example a user is selling in DAI-WETH market.

They would select DAI as sell token, WETH as buy token, and we would show the price in WETH, when usually users would expect the price to be in DAI (they would call this action buying in WETH-DAI market)

**Comment by anxolin** [comment]
@Velenir  implemented this PoC to try to unify the price and use the BASE/QUOTE price by default, being BASE the buy token, QUOTE the sell token (since we don't have canonical markets, and implement sell/buy orders)

https://pr1143--dexreact.review.gnosisdev.com/

If the QUOTE is not the token you expect, you can still invert the price:
![image](https://user-images.githubusercontent.com/2352112/85384694-af7e1980-b541-11ea-90a7-9584fb01b983.png)


This doesn't solve all the issues, but it's closer what the users expect from the feedback we have received. This follows Uniswap approach.

For solving the issues, imo this UI should change the workflow, and you should:
- start by selecting a market (canonical)
- place a limit order: sell or buy
- layout should be like all the trading UIs: there's kind of a pattern for these apps

**Comment by alfetopito** [comment]
Addressed on #1138 and released on #1143
