### ISSUE TITLE
Check Metamask compatibility

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#1199]
# Check Metamask compatibility

Make sure we are compatible with the Metamaks breaking changes

_Estimation: 1_

**Comment by Velenir** [comment]
Summary of **MetaMask** deprecated API:
https://docs.metamask.io/guide/ethereum-provider.html#legacy-methods

Transaction sending methods:
* We rely on `send|sendAsync` and can't replace it,even conditionally, because afaik **web3** operates with send not request
* **Web3** providers (**HttpProvider**, **WebSocket** provider) only implement send
* **json-rpc-engine** which we use for composing providers, uses `send/sendAsync`, though that part is easy to change
* all other injected providers (on mobile), who knows when they'll implement request
* last time I checked WalletConnect.request is a bit different in signature from `send|sendAsync`, so can't just fallback` (p.request || p.send || p.sendAsync)(params)
`
`Provider.enable()`:
* we also rely on enable method, directly in autoconnect, and through **Web3Connect**
* it probably won't go away anytime soon, so it's ok to keep it
* **web3connect** will likely do something to accommodate request in the future
* so we should stiop using `.enable()` directly, only through **web3connect**
* **WalletConnect** handles enable differently from `request({ method: 'eth_requestAccounts' })`, so not equivalent for now

`Provider.on()` events:
* events, we already listen for `chainChanged`, so we are good there
* subscription results **MetaMask** actually emits in data event, not in `notification|message` event, doesn't matter **web3** uses what is right internally

`ethereum._metamask` object:
* we used to get some data from `ethereum._metamask` object back in **dapp-ui** times, not relevant anymore
* warning in console **MetaMask** will soon stop reloading pages on network change doesn't matter
* we do set `ethereum.autoRefreshOnNetworkChange= false` in `WalletApi`, but that happens a bit later than the warning
* warning appears on page load (when **MetaMask** extension is injected into window)

Summary of summary:
* new **MetaMask** methods are only available with version >= 8
* so only **Firefox** for now
* legacy will continue working

All in all because of provider feature disparity I think we should do the following:
1. Keep legacy methods
2. Wait until libraries (**web3**, **web3connect**) add support for new methods
3. Watch out for bugs as they happen
4. Stop calling `provider.enable` in `autoconnect`, instead rely on **web3connect** to do that work for us (#1210)


@alfetopito @anxolin @W3stside , thoughts?

**Comment by alfetopito** [comment]
Great summary. 

Let's do only what's needed, if any. Given there's little support for new apis at this point.
Which is only step `4` as I understand.

**Comment by anxolin** [comment]
This is an amazing summary, it will make it easier for the transition. 
Okay, so I would suggest Dima you create a recurrent calendar event, every 6 weeks with a link to this issue, and we reevaluate.
This way, we can keep a better track of the changes and we leave some time to WC to catch up and this transaction process to take a better shape.

Does it make sense?
