### ISSUE TITLE
COMP token enable for deposit each time after log in

### ISSUE THREAD

**Issue by ykplayer8** [gnosis/dex-react#1229]
One user report that he should enable COMP deposit every time after new log in to Mesa.
He successfully deposited COMP several times and every time he made new COMP approving 
This issue just with COMP token

**Comment by alfetopito** [comment]
Sounds similar to one issue we had with DMG token (https://github.com/gnosis/dex-react/pull/1147)
This was part of the hotfix during the sale though.

**Comment by alfetopito** [comment]
https://etherscan.io/address/0xc00e94cb662c3520282e6f5717214004a7f26888#code

```sol
    /// @notice Allowance amounts on behalf of others
    mapping (address => mapping (address => uint96)) internal allowances;
```

**Comment by alfetopito** [comment]
Let me see if I can get the math right.

A token is considered enabled when `userAllowance` >= `tokenAllowance`.

- `userAllowance` is fetched from the contract for each user/token.

- `tokenAllowance` is given by: `10 ** (tokenDecimals + 12)` = 10 ** (18+12) = `1000000000000000000000000000000`

The max allowance `COMP` user can have is the max uint96 => `2 ** 96 - 1` == `79228162514264337593543950335`

`79228162514264337593543950335` is not >= `1000000000000000000000000000000`, thus the token is considered not enabled.

Oh well, have to revisit this again...







In the case of this token, it'll never be, because allowances are stored as uint96.
