### ISSUE TITLE
Review gas price estimation

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#1313]
Seems like our gas price estimation is too low.
Some users are having issues where txs are pending over one hour, even though they used the gas price suggested by us.

Reported using Metamask, suggested gas price 154, current gas price 170.

![photo_2020-08-10_11-03-36](https://user-images.githubusercontent.com/43217/89815172-2a52c200-daf9-11ea-9f37-c6698ac4a9c3.jpg)

![photo_2020-08-10_11-03-41](https://user-images.githubusercontent.com/43217/89815169-29219500-daf9-11ea-86b3-71960b49e3c8.jpg)

**Comment by Velenir** [comment]
What is our gas station reporting at the same time?

**Comment by alfetopito** [comment]
> What is our gas station reporting at the same time?

According to the user, it was 154 (the value in the Metamask screenshot)

**Comment by Velenir** [comment]
Would be interesting to see all the values from the gas Stanton. We may need to switch from standard to fast,or at least standard*1.5

**Comment by anxolin** [comment]
I guess this can happen if there's sudden changes (because it uses the quartiles of several blocks), but so far, the service was working very reliably in all services and webs.

@Uxio0 is it possible to check what was the price at the time.

**Comment by Uxio0** [comment]
@anxolin You can use gas station history, e.g. https://safe-relay.gnosis.io/api/v1/gas-station/history/?fromDate=2020-08-10T17%3A30%3A00Z&toDate=2020-08-10T18%3A15%3A00Z

**Comment by anxolin** [comment]
Thanks uxio, yes, we checked back then. We believe that in some percentage of cases, the estimation fails to make the transaction to be mined using the "standard". 

These cases become very vocal during the IDOs and make some noise. Some people, managed to get a real "tx jam" queue.

We wouldn't like to increase the gas, because these would bring us to another set of complaints for high prices.

This is the relevant conversation we had: https://gnosisinc.slack.com/archives/C63LQTGNB/p1597130084391000

Somewhat related discussion about this other service that uses a "predictive model", that takes the mempool into account. 
There, I suggest how we tell better how good is our strategy. The idea goes in the direction of using a prometheus metric to measure the values that are returned for every block, as opposed to what the actual gas prices are for the next ones.
https://gnosisinc.slack.com/archives/C58AGV3HA/p1597310624051500

If we have this metrics, and we want to tackle this, we can see how other strategies like a linear regression would behave. A linear regression could be better capturing up trends.

**Comment by Uxio0** [comment]
@anxolin I think this is really a good idea, I would like to experiment with new algorithms, maybe not replacing the one we have but adding new ones so we can test all them and check how they are working
