### ISSUE TITLE
Get the minimum trade amount in USD from the backend

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1380]
![image](https://user-images.githubusercontent.com/2352112/92246086-8ecd2b00-eec5-11ea-8ae2-61cd46ddcc22.png)

The app is showing the minimal trade in USD as a dynamic value that computes taking some parameters into account (gas price, ether price in OWL, subsidy factor, etc..)

The solvers will be changed into using a fixed amount in USD as the minimal trade. This value will be exposed from a backend endpoint so solvers and front end are more aligned.

It's likely that in the future we use this calculation again, but for now it should to change into a fixed value coming from the backend.

More details in. this slack thread
https://gnosisinc.slack.com/archives/CC3C5SMB5/p1599224119069800?thread_ts=1599223469.068400&cid=CC3C5SMB5

@e00E @fleupold  can you let us know the signature of the endpoint in advance, so we can mock it while is not implemented?

**Comment by e00E** [comment]
I interpreted the slack conversation so that we would only use the fixed amount for that one specific time period but in general we'll stay with the factor. And I'm not sure if we will have that endpoint by Wednesday (but we will have the hard coded number in the solver).
Not exactly what the format would be but I imagine something like `GET http://solver-constants.../`
```json
{
    "economic_viability_factor": 5.0,
}
```

but then if we have to differentiate fixed and factors maybe

```json
{
    economic_viability_factor: {
        "fixed": 1000
}
```

and 
```json
{
    economic_viability_factor: {
        "factor": 5.0
}
```

**Comment by anxolin** [comment]
I've missed this message, yep sounds good to me.

What about a slight change in the data structure, like `<BASE_URL>/economic-viability-factor`:
```json
{
    "type": "fixed-owl",
     "amount": 2500
}
```

```json
{
    "type": "subsidy-factor",
     "amount": 5.0
}
```

**Comment by anxolin** [comment]
We are having this conversations now in 2 places. Let's continue here https://github.com/gnosis/dex-react/pull/1383
