### ISSUE TITLE
Switch contract API methods to accept Object arguments

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#193]
Seen an issue in `erc20API.approve(senderAddr, tokenAddr, spenderAddr)` where the func params were mixed up leaving a hard-to-debug issue.

I propose switching to Object parameters i.e

`erc20API.approve({ senderAddr: string, tokenAddr: string, spenderAddr: string })`

**Comment by W3stside** [comment]
Would prevent hard to debug code errors

**Comment by bh2smith** [comment]
I like this idea and would be in favour of such an improvement!

**Comment by anxolin** [comment]
Good point.

Yes, I agree. We had a chat the other day. The object-like params approach would be applicable for any non-trivial util/lib/api since although typescript helps a bit to check and document the params, if they have the same type, it would allow to switch the positions messing it up and as David says, making it very difficult to debug.
