### ISSUE TITLE
Consider Including More Decimal Places On Price

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-react#347]
In the below screenshot, it may be nice if the UI displayed `1 DAI = 1.001 TUSD`. Maybe it would beneficial to include more decimal places. 6 or 8 seams good to me.

![issue](https://user-images.githubusercontent.com/4210206/71367611-e29d1b80-25a5-11ea-9508-5e6cf881a64a.png)

**Comment by anxolin** [comment]
Yes, I agree

**Comment by anxolin** [comment]
Sorry Nick, we had this planned for this sprint, but it got re-arranged because of some new prioritization

We wanted to provide a fancy solution that gives you different decimals depending on the amount, but we'll make a trivial solution: add a couple of decimals for now, being stable coins I think should be good enough for now
