### ISSUE TITLE
Issue with locale and `use max` button

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#691]
I understand from this comment we have an issue with the locale:
https://github.com/gnosis/dex-react/issues/500#issuecomment-594522648

`use max` uses an English/America format for numbers, while the inputs and validation expects the local user's locale, this is causing the form validation to fail, so the user has to modify the symbols manually.

**Comment by alfetopito** [comment]
Wondering what's the best approach:

1. Make the inputs accept locale aware numbers
2. Keep a single default locale for inputs, and when clicking `use max` insert appropriated value instead of locale dependent amount.

`2` would for sure be simpler to implement, without the need to update all the validations to be locale aware.

Uniswap inputs for instance are not locale aware:

![Captura de tela de 2020-03-12 14-16-43](https://user-images.githubusercontent.com/43217/76567542-33693580-646c-11ea-8ceb-e25f0f167d00.png)

I'm inclined to `2` mainly for ease of implementation (shame on me), but I'm not sure that's the best UX.

@anxolin @c3rnst thoughts?

**Comment by Velenir** [comment]
Let's enforce ONE TRUE LOCALE -- our locale, without commas

**Comment by anxolin** [comment]
Okay, if it's simpler and "others are doing it", let's go for simpler approach :)
