### ISSUE TITLE
Unreliable enable token process

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#758]
It happens sometimes that:

1. Click on enable token
2. Changes to "Enabling...", the spinner works for some seconds (i.e. 30s)
3. Suddenly goes back to show "Enable token". The user is unsure if it's enabled or not, or if he has to click again
4. Some time later (i.e. 15s) the button disappears, and it shows that the token has been enabled

**Comment by alfetopito** [comment]
I was able to reproduce, although with shorter times. 

The issue happens due to the delay between confirming the tx and updating token states.
Each is done in a separated context.

[`enabling` flag](https://github.com/gnosis/dex-react/blob/develop/src/components/DepositWidget/Row.tsx#L134) is set/unset on [`useRowActions` hook](https://github.com/gnosis/dex-react/blob/develop/src/components/DepositWidget/useRowActions.tsx#L55), which depends on the tx receipt and mining respectively.

[`enabled` flag](https://github.com/gnosis/dex-react/blob/develop/src/components/DepositWidget/Row.tsx#L122) is set/unset on [`useTokenBalances` hook](https://github.com/gnosis/dex-react/blob/develop/src/hooks/useTokenBalances.ts#L61) which is updated on every block change.

AFAIK tx mining and a new block are the same thing, but this is handled at different levels in the app, leading to the delay in updating the value on the interface.

**Comment by Velenir** [comment]
Idea:

- only use `useRowActions` for enabling flag
- Maybe with useTokenBalances for initial value, maybe not even
- Persist enabling state in GlobalState if needed

**Comment by alfetopito** [comment]
> Idea:
> 
>     * only use `useRowActions` for enabling flag
> 
>     * Maybe with useTokenBalances for initial value, maybe not even
> 
>     * Persist enabling state in GlobalState if needed

For 1 and 3, `enabling` is already on the global state and is mutated only on `useRowActions`.

If you mean `enabled`, though, yeah, I could do that. Messy but could work.
- Add `enabled` to global state
- Use `useTokenBalances` for initial value as you said on `2`
- Set `enabled` true when tx is confirmed on `useRowActions`.

**Comment by Velenir** [comment]
> If you mean `enabled`

Yep, yep, good job!
