### ISSUE TITLE
Suggested improvements to 'Your orders' section under 'Trade' tab

### ISSUE THREAD

**Issue by cmagan** [gnosis/dex-react#814]
1. The orders are sorted such that older orders are at the top. It's much more convenient to see the recent at the top. Would also be nice to have the "Expires" and "Status" headers clickable so the user can decide by what category to sort and in which direction
![image](https://user-images.githubusercontent.com/6940448/78191250-488b2000-747e-11ea-9785-a84b4ab4e95d.png)

2. When scrolling down, the headers (active, liquidity, closed) are disappearing. Would be nice to see them also when scrolling down

3. When scrolling down the text of headers is overlapping with order data

![tempsnip](https://user-images.githubusercontent.com/6940448/78191653-22b24b00-747f-11ea-9474-43860cbc5cbd.png)

**Comment by anxolin** [comment]
Thanks for the feedback!

1. Agree on the default sort order. Also that change sorting is a nice feature. Ideally even filtering by status.

2. Yes, agree.

3. Yes, we are aware, there's an issue for that #798. I think this unrelated PR #792 solves the issue

**Comment by anxolin** [comment]
I broke this into issues, please close this one if the ideas are captured in those issues.

https://github.com/gnosis/dex-react/issues/820
https://github.com/gnosis/dex-react/issues/821
https://github.com/gnosis/dex-react/issues/822
https://github.com/gnosis/dex-react/issues/823

@cmagan  Keep the feedback coming, if possible. Make a quick search if it's there already, if not, ideally we prefer independent issues, instead of unrelated ones. 

Not sure if your are dev, but we also accept PRs
