### ISSUE TITLE
Proposal for: Why my order didn't match??

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#931]
So one issue right now is, in some situations the order doesn't get matched, and the user has no idea at this point if it's a matter of minutes or it won't ever get matched

TLDR: The proposal is to check the current price for your open orders, and show if the price is OK or not. 
* If iser's order is more pricey, show something like "XX% over the current offers"
* If user's order is less pricey, maybe show the price in a green color

Here is an example of an user's workflow:
1. I want to exchange 0.03 WETH for WBTC
2. Submitted the order at the suggested price: 0.0245
3. The trade wasn't matched. As a user, I have no idea why
4. I checked the price again of the same order 0.03 WETH for WBTC, now I get a worse price 0.0242, AHAA!!, now I know why my order didn't match, the price changed. If only the UI would tell me instead of me checking...

![image](https://user-images.githubusercontent.com/2352112/79541416-11c22600-808a-11ea-9016-536895db2cf3.png)

cc/ @c3rnst @alfetopito @koeppelmann @Rafanator @biocom

**Comment by Velenir** [comment]
That is a good idea, but I'm really not a fan how Orders UI is getting busier by the minute, all in that small space.
Maybe an alert-like icon for each order, clicking on which opens a modal with more info. Instead of cramming everything in the row.

On possible implementation:
1 after each batch ends, request price estimate for each row, or for common token pairs among all rows?
2 display alert if anything amiss (can even incorporate low balance alert into that one)
3 more info on alert click

**Comment by anxolin** [comment]
Yes, agree. Maybe we could re-think if we still want the alert of the balance. I think it's mostly annoying and if we add another alert, it gets more confusing.

Probably @biocom have a proposal on how to show this nicely.I know Kraken for example tells you this kind of info for open orders. A small research on how other tools do it can be beneficial.

**Comment by Rafanator** [comment]
I like Anxo's idea, would like to see how it looks implemented because I also think it could get cluttered soon. 

For future inspiration, [dy/dx](https://trade.dydx.exchange/) has the best interface IMO. Take a look at how they handle the Positions/Blanaces/Ordes/Fills for inspiration.
