### ISSUE TITLE
Analyse failing transaction

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#974]
Review the failing transactions from the contract, and see if there's a workflow that leads to it in the web

@Velenir @anxolin please add any more details im not familiar anymore with this one

**Comment by W3stside** [comment]
`Est 1`

**Comment by alfetopito** [comment]
It seems it's not possible to see the failing transactions on etherscan:

https://etherscan.io/txs?a=0x6f400810b62df8e13fded51be75ff5393eaa841f

![screenshot_2020-05-12_14-13-08](https://user-images.githubusercontent.com/43217/81746082-bb62c000-945a-11ea-997e-30f942bf990d.png)

Where else should I be looking at?

**Comment by alfetopito** [comment]
Found a block explorer where I can filter by failed transactions https://blockchair.com/ethereum/calls?q=recipient(0x6f400810b62df8e13fded51be75ff5393eaa841f),failed(true)#

**Comment by alfetopito** [comment]
Analyzed ~200 failing transactions from May 1st until today (May 13th).

### Query

Filtered out falling transactions with Child calls == 0, as those (on the majority of the subset I checked) are solvers submitting solutions. Example: https://etherscan.io/tx/0x43d5357581556513a0a1e8f3e1eed09a4cd4318233ffbf980169ba0396d3995e

1. [Without the filter](https://blockchair.com/ethereum/calls?q=recipient(0x6f400810b62df8e13fded51be75ff5393eaa841f),failed(true),child_call_count(1..)#f=block_id,transaction_hash,index,time,child_call_count,type,failed,transferred,sender,recipient,value,value_usd) there are in total 2578 failed txs.

2. [With Child calls >= 1](https://blockchair.com/ethereum/calls?q=recipient(0x6f400810b62df8e13fded51be75ff5393eaa841f),failed(true),child_call_count(1..)#f=block_id,transaction_hash,index,depth,time,child_call_count,type,failed,fail_reason,sender,recipient) there are 709

### Addresses submitting failed solutions

```
0x0f833795b7597fcb7f22d8278c91ef63d441e949
0x36f7c5b5b8d66cec99e1282dd1c069648a0d4637
0x453ad119f26128034d3b5c2b6179b8b7f63ae1c7
0x5a30ff01dc11223cff4e99d4263cb6f3aaa69e70
0x665316dabde5c5bc57ad0b2eed523447c5d2a570
0x9ee11fccd3f692d1ddb281d81403b7e08b964c76
```

So I ignored txs coming from any solver.

### Bots

Out of those (child call >=1), several are coming from known bots, by Gnosis or third parties, such as the addresses

```
0x5ce64e024d54eee4e6409829cf0ff8529e5da170
0x9f8157fee385f3620e5f3a259cd4851089305605
0xeb13c6ff42f1307c026a7f6e2c97068658d9aea6
0xf50a3cfd68a00009623e1767eb696c4cc9347a7d
```

### Add token to exchange

One case that might be an indication we need to improve our docs is a user failing to add a token to the contract:

- Account: `0x298e24e6da949b2014191c767ca044178df9973e`
- Failed tx: https://etherscan.io/tx/0x8c3240bb25ae1140002c239148c1e97dbef0e222d91b8819c4917e075fe640ba

Probably got confused how to do it.
Deposited 10OWL in the contract and later withdrew it.
My guess is the failure above (on `addToken` operation) was because he had no OWL in his wallet, having instead depositing it on the contract.

### Fail to deposit

There was at least one case of failure to deposit on the contract, likely due to lack of approval:

https://etherscan.io/tx/0x07dc5614a053a177370964f0b62bc4f3919de1d2dcdf779beb3f61d81b32009b

### Probable UI related failures

I found 3 instances of accounts failing to submit `validFrom` orders, which from the parameters used I deduce were liquidity orders:

1. `0x938728abc0bd173b8a4f07813810e224a5c3c166`
https://etherscan.io/tx/0x325f010aaff8bc983fed0d725607c3b9a99218d7ea6a6b579a715e73ad09296f
This tx was "sped up" as indicated by the fact that another tx with same nonce was replaced by it: 

>  Also found 1 Other Dropped Txn #1 with the same `From` Account Nonce

2. `0x75bbc7d37d3bf975b527cf2e99b947d61a22ef95`
https://etherscan.io/tx/0xd09606efe40cd4f4170f1e2b585b24c2c2a46aba585e2c6cb95d5ac5a19e4ee8
Same as previous

3. `0xc50eaaee441566b4ef4f1e3270d19f24223cddf4`
https://etherscan.io/tx/0xeaa0952efb3a0b9fa88bc76e4e7a037b72fe6d438e768b130d7592b4a44d6c18
Same as previous.
This address deposited 1k USDC and 5h later withdrew it.
Failed to create liquidity with 6 stable coins. Managed to create one with 3.
